image: docker:latest
variables:
  DOCKER_COMPOSE_PATH: /opt/docker/$CI_PROJECT_NAME
services:
- docker:dind

stages:
- build
- deploy

build:
    stage: build
    script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID
    only:
    - deploy
    when:
    - manual
    
    
deploy_to_production:
    stage: deploy
    script:
    - ssh $PROD_USER@$PROD_HOST "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - ssh $PROD_USER@$PROD_HOST "docker pull $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID"
    - scp docker-compose.yaml $PROD_USER@$PROD_HOST:$DOCKER_COMPOSE_PATH/docker-compose.yaml
    - >
      ssh $PROD_USER@$PROD_HOST 
      "TAG=$CI_PIPELINE_ID
      PORT=$PORT
      POSTGRES_DB=$POSTGRES_DB
      POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      POSTGRES_USER=$POSTGRES_USER 
      docker-compose -f $DOCKER_COMPOSE_PATH/docker-compose.yaml up -d"
    only:
    - deploy



