spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: 172.28.142.5
    port: 25
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
  jpa:
    generate-ddl: true
    database: POSTGRESQL
  config:
    import: optional:prod.yml


security:
  jwt:
    token:
      secret-key: jwtapp
      expire-length: 14400000
  require-ssl: true

server-config:
  upload-path: '/var/lib/docker/volumes/psg-volume/_data'
