spring:
  datasource:
    url: jdbc:postgresql://psg/sks_recruiting
    username: postgres
    password: 5Rag^ycn
    platform: postgres
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: 172.28.142.5
    port: 25
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
  jpa:
    generate-ddl: true
    database: POSTGRESQL

security:
    jwt:
      token:
        secret-key: jwtapp
        expire-length: 14400000
    require-ssl: true

server-config:
  upload-path: '/var/lib/docker/volumes/psg-volume/_data'

server:
  ssl.key-store: classpath:ira_test.jks
  ssl.key-store-password: 3edcVFR$
  ssl.keyStoreType: JKS

#    location: '${user.dir}/uploads'
#    prodLocation: '/var/lib/docker/volumes/psg-volume/_data'
#    10.16.230.116
#    172.28.142.101
#    172.28.142.5
#    sks_recruiting
