spring:
  datasource:
    url: jdbc:postgresql://psg/sks_recruiting
    username: db_recruiting
    password: 5Rag^ycn
    platform: postgres

server:
  ssl.key-store: classpath:beeline.jks
  ssl.key-store-password: 3edcVFR$
  ssl.keyStoreType: JKS


  #    location: '${user.dir}/uploads'
  #    prodLocation: '/var/lib/docker/volumes/psg-volume/_data'
  #    10.16.230.116
  #    172.28.142.101
  #    172.28.142.5
  #    sks_recruiting